version = 1
SPDX-PackageName = "Novus"
SPDX-PackageSupplier = "Joshua Goins <josh@redstrate.com>"
SPDX-PackageDownloadLocation = "https://github.com/redstrate/Novus"

[[annotations]]
path = ["apps/armoury/geareditor.rc", "apps/karuku/exceleditor.rc", "apps/sagasu/dataexplorer.rc", "apps/mapeditor/mapeditor.rc", "apps/enemyeditor/enemyeditor.rc", "apps/patchdiff/patchdiff.rc"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Joshua Goins <josh@redstrate.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [".gitmodules", "scripts/**", "README.md", "BUILDING.md", "CONTRIBUTING.md", "apps/armoury/README.md", "apps/karuku/README.md", "apps/sagasu/README.md", "apps/enemyeditor/README.md", "renderer/README.md", "apps/sdklauncher/README.md", ".clang-format", ".build.yml", "misc/**", "renderer/shaders/**.spv", "apps/mapeditor/README.md", ".github/**", "apps/patchdiff/README.md", "zone.xiv.novus.yml", "zone.xiv.novus.appdata.xml", "REUSE.toml", "CODE_OF_CONDUCT.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Joshua Goins <josh@redstrate.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["apps/armoury/zone.xiv.novus.geareditor.svg", "apps/karuku/zone.xiv.novus.exceleditor.svg", "apps/sdklauncher/zone.xiv.novus.sdk.svg", "apps/mapeditor/zone.xiv.novus.mapeditor.svg", "apps/sagasu/zone.xiv.novus.dataexplorer.svg", "resources/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Joshua Goins <josh@redstrate.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "extern/tinygltf/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 Syoyo Fujita"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "extern/magic_enum/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 - 2023 Daniil Goncharov"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "extern/imgui/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014-2023 Omar Cornut"
SPDX-License-Identifier = "MIT"
