version = 1
SPDX-PackageName = "Novus"
SPDX-PackageSupplier = "Joshua Goins <josh@redstrate.com>"
SPDX-PackageDownloadLocation = "https://git.sr.ht/~redstrate/novus"

[[annotations]]
path = ["apps/armoury/geareditor.rc", "apps/karuku/exceleditor.rc", "apps/mdlviewer/mdlviewer.rc", "apps/sagasu/dataexplorer.rc", "apps/mapeditor/mapeditor.rc", "apps/mateditor/mateditor.rc"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Joshua Goins <josh@redstrate.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [".gitmodules", "scripts/**", "README.md", "BUILDING.md", "CONTRIBUTING.md", "apps/armoury/README.md", "apps/karuku/README.md", "apps/sagasu/README.md", "apps/mdlviewer/README.md", "renderer/README.md", "apps/sdklauncher/README.md", ".clang-format", ".build.yml", "misc/**", "renderer/shaders/**.spv", "apps/mapeditor/README.md", ".github/**", "apps/mateditor/README.md", "zone.xiv.novus.yml", "zone.xiv.novus.appdata.xml", "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Joshua Goins <josh@redstrate.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["apps/armoury/zone.xiv.armoury.svg", "apps/karuku/zone.xiv.karaku.svg", "apps/sdklauncher/zone.xiv.novus.svg", "apps/mapeditor/zone.xiv.mapeditor.svg", "apps/mdlviewer/zone.xiv.mdlviewer.svg", "apps/sagasu/zone.xiv.sagasu.svg", "resources/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Joshua Goins <josh@redstrate.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "extern/tinygltf/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 Syoyo Fujita"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "extern/magic_enum/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 - 2023 Daniil Goncharov"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "extern/imgui/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014-2023 Omar Cornut"
SPDX-License-Identifier = "MIT"
